### PR TITLE
Update main.rs

### PR DESCRIPTION
**Pull request by BonfireScratch**
If the code is appropriate, merge it. Else, delete it

### CODE REVIEW

**Comment by SimpleBinary** [comment]
@BonfireScratch Failing.

**Comment by Dandigit** [comment]
@BonfireScratch This would have been super useful - but unfortunately, I've already started writing a lexer and have written more or less the same thing.

**Comment by BonfireScratch** [comment]
@Dandigit it's alright!

**Comment by BonfireScratch** [comment]
@Dandigit btw can a compiler be written in a non-compiled language? (eg. Python or Lisp)

**Comment by Dandigit** [comment]
@BonfireScratch Most definitely, yes. LLVMPy is a very popular LLVM binding for this.

**Comment by BonfireScratch** [comment]
@Dandigit how much time have you spent on GWN?!?

**Pull request closed without merging**
